/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiSearchRouteImport } from './routes/ai-search'
import { Route as LeadRouteImport } from './routes/lead'
import { Route as AuthenticatedAdSpendRouteImport } from './routes/_authenticated/ad-spend'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as AuthenticatedAdminOverviewRouteImport } from './routes/_authenticated/admin.overview'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSearchRoute = AiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadRoute = LeadRouteImport.update({
  id: '/lead',
  path: '/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdSpendRoute = AuthenticatedAdSpendRouteImport.update({
  id: '/_authenticated/ad-spend',
  path: '/ad-spend',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/_authenticated/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/_authenticated/appointments',
    path: '/appointments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/_authenticated/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminOverviewRoute =
  AuthenticatedAdminOverviewRouteImport.update({
    id: '/_authenticated/admin/overview',
    path: '/admin/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/_authenticated/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/_authenticated/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-search': typeof AiSearchRoute
  '/lead': typeof LeadRoute
  '/ad-spend': typeof AuthenticatedAdSpendRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-search': typeof AiSearchRoute
  '/lead': typeof LeadRoute
  '/ad-spend': typeof AuthenticatedAdSpendRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-search': typeof AiSearchRoute
  '/lead': typeof LeadRoute
  '/_authenticated/ad-spend': typeof AuthenticatedAdSpendRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/_authenticated/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-search'
    | '/lead'
    | '/ad-spend'
    | '/analytics'
    | '/appointments'
    | '/dashboard'
    | '/pipeline'
    | '/properties/$id'
    | '/properties/'
    | '/admin/overview'
    | '/leads/$id'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-search'
    | '/lead'
    | '/ad-spend'
    | '/analytics'
    | '/appointments'
    | '/dashboard'
    | '/pipeline'
    | '/properties/$id'
    | '/properties'
    | '/admin/overview'
    | '/leads/$id'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-search'
    | '/lead'
    | '/_authenticated/ad-spend'
    | '/_authenticated/analytics'
    | '/_authenticated/appointments'
    | '/_authenticated/dashboard'
    | '/_authenticated/pipeline'
    | '/properties/$id'
    | '/properties/'
    | '/_authenticated/admin/overview'
    | '/_authenticated/leads/$id'
    | '/_authenticated/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiSearchRoute: typeof AiSearchRoute
  LeadRoute: typeof LeadRoute
  AuthenticatedAdSpendRoute: typeof AuthenticatedAdSpendRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  AuthenticatedAdminOverviewRoute: typeof AuthenticatedAdminOverviewRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-search': {
      id: '/ai-search'
      path: '/ai-search'
      fullPath: '/ai-search'
      preLoaderRoute: typeof AiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead': {
      id: '/lead'
      path: '/lead'
      fullPath: '/lead'
      preLoaderRoute: typeof LeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ad-spend': {
      id: '/_authenticated/ad-spend'
      path: '/ad-spend'
      fullPath: '/ad-spend'
      preLoaderRoute: typeof AuthenticatedAdSpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/overview': {
      id: '/_authenticated/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiSearchRoute: AiSearchRoute,
  LeadRoute: LeadRoute,
  AuthenticatedAdSpendRoute: AuthenticatedAdSpendRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  AuthenticatedAdminOverviewRoute: AuthenticatedAdminOverviewRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
